services:
  saures-client:
    image: ${DOCKER_USERNAME}/saures-client:${TAG}
    container_name: saures-client
    restart: always
    environment:
      TZ: Europe/Moscow
      SAURES_API_URL: ${SAURES_API_URL}
    env_file:
      - .env
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.saures.rule=Host(`saures.housekpr.ru`)"
    networks:
      - housekpr-network

networks:
  housekpr-network:
    external: true
